### PR TITLE
Bug/fix api key issues

### PR DESCRIPTION
**Pull request by shermanjoshua**
## OVERVIEW

This plugin has stopped working for many folks, myself included. I wanted to offer up a fix, but not invest a ton of time, so I got this running _beginning from the nodejs branch in this repo._ I did not spend a ton of time testing or checking edge cases, making things "pretty," or adding new functionality. This was purely a convenience for myself - but now that I've done this I do intend to add things/maintain a little bit if folks find it useful. 

Basically the changes were:
* Add the new version of the sdpi library
* Updates to the UI components for the new library
* Updates to make the API key validation process work again
* A little bit of reorganization here and there with the INTENT of making future updates easier. (_INTENT_ doesn't mean I accomplished anything of the sort... even remotely 😆)
* I made a pass at a wrapper function for `sdpi-item` which I would probably submit to that project... if I had got it working 😞 It would make things MUCH easier for newbies to the ecosystem if that was available as a fluent function to add.... or maybe even better it could be an **opt-out** thing because it's far more likely folks will USE the styling rather than not... but that's a discussion for that project and at some other time.

I have like 3 Govee devices so that is all I have tested with. I don't know what the testing protocol is like for real world maintenance of this, but I imagine it is more than that. I'd love to add some automated testing to this project - and some developer helpers to do things like reset the state of your connected device on rebuild/restart when you are in dev mode, etc. to make manual testing faster... but alas I didn't have time for that either.

I'm not sure if this repo is abandoned at this point or not, but I hope not! I'm going to advertise my fork in an issue on this project if this doesn't get merged/commented any time soon. **PLEASE FEEL FREE TO TELL ME NOT TO OR TO DELETE ANY ADVERTISING IF YOU WANT ME TO STOP!!!** It's not my intent to step on toes or horn my way in, I just see a few people having this problem and want to offer them a solution if they want it. 

Thank you for this plugin, and thanks for looking at my little PR.

### CODE REVIEW

**Comment by GeekyEggo** [comment]
Hey @shermanjoshua, thanks so much for your contributions; the Node.js re-write has been at the finish line for a while now, and I'm happy to say I've just submitted it to Elgato for review. If all goes well, it should be on Marketplace shortly. ❤️

**Comment by shermanjoshua** [comment]
> Hey @shermanjoshua, thanks so much for your contributions; the Node.js re-write has been at the finish line for a while now, and I'm happy to say I've just submitted it to Elgato for review. If all goes well, it should be on Marketplace shortly. ❤️

Oh that's awesome news! Congrats to the team. 

Unfortunately, that was the one that wasn't working anymore for many of us. I'll certainly check it out again when it's on the store though just to make sure it wasn't just user error or something else causing the API Key entry issues. 

Congrats again, and appreciate all the work on the deck and these plugins.

**Comment by GeekyEggo** [comment]
The re-write also updates the API usage to use the latest API, so should resolve a lot of the issues users were experiencing (and also add support for a lot of new devices).

You can test this now by downloading the [.streamDeckPlugin](dist/com.geekyeggo.goveecontroller.streamDeckPlugin) file.

**Comment by shermanjoshua** [comment]
Tested and can confirm it is working. May want to check the date/time stamp that was published in it, as I'm guessing it could cause issues with auto-updates if your tools check that....

I had a blast working on this - I've been in the industry for 20 years, but I've been exec/sr management so long now that I always worry I've forgotten how to code altogether. It was fun to check out some of the stuff in here and have a well-defined "thing" to work on! Plus I dig the almost convention-based nature of naming everything. Very familiar feeling...

I missed the scene buttons and I've always wondered why there was never an option to select Snapshots, so I took a little time and went ahead and got that stuff working. It's [out on my fork](https://github.com/shermanjoshua/GoveeController) if you want to check it out. And NOW I know why there were no Snapshots included originally 😃 Didn't take long, but had to figure out a strategy that made sense for sure.

Thanks again for all the work you all do on this stuff.

**Pull request closed without merging**
